### ISSUE TITLE
hi, 

### ISSUE THREAD

**Issue by DONG-Jason** [Eric991005/Stockformer#1]
hi, when I trying to make this project working, I found a mistake here.
The python file, graph_utils.py, is missing, 
from lib.graph_utils import loadGraph

Can you help me?
thx a lot.

**Comment by Eric991005** [comment]
Hi,

Thank you for bringing this to my attention. I've realized the mistake and have now uploaded the missing `graph_utils.py` file to the repository. You should be able to import `loadGraph` from `lib.graph_utils` without any issues now.

Please try pulling the latest changes from the repository. If you encounter any further issues or have any questions, feel free to ask.

Thanks again for your patience and support.

Best,
Eric
